runtime: nodejs16 
env: standard 
instance_class: F2 

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

env_variables:
  FIREBASE_PROJECT_ID: "ingrevia"
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCurMXobvVsvNoa\nPO2Xd+5aTRgjnzxn6ORAir8OpfUIpX/bi0RSlG+uWM13o1yJ7S2hFG/C8nEdvr11\n01sWnTLFZqyoYFUTr/sYcafVFpJMtRZW4kFspSaZ4/y7r1NspidgmrKuFMckJP24\nEOEuPwcIykeY2R1ot5DaRQEZn9ZzDQoL0RzExb3ekL4QM8QsMHc1qnkwuo2h4OrZ\ngr+rDpdIXYhR/tOq2T9CGhpYBqoEzYaDrMVmGQzCkPpwFyHLLopt42v297GNlzDw\njz8GNlAzSn8/k10hxhGIWEe9NksbdWlfFR25wPVyhJJauWzQHUQyiHJ7ShNpgP3B\njtNKzJdfAgMBAAECggEAPvOPY8RReP3a0KfyrKsRYMP2Fih2ObCqSkR2tM3EsHgM\ny0+2sNhEI55ndl2OpTqwPiRCXwzHDYRHfaZNZqoCuTfWs9v77Vt38AhOBzLaSQDe\nazOhholCjyWmWPHH7Bk5icxW5vwgBPu74NFchjE61MUp5oEg4zN85d0Gl3iObenF\nqy8FFdMmDlfbmwBzpilRlzY7rNS5xbvNan66hkK+bIc5gj+esIlmr45Vr8Xw1fK3\ngv0RO208JLKCwdkFMAgJCn5UHcM9UQxuU/VgvXy94BFoMCdq1OPqWYhQ4HtIa0AC\nD4XoGxMr3HoTdGr2AVN+UNYXiVlZTDq2/MaftPAsQQKBgQDW3SVmohbJbXFCiR0V\nmAZWcKIFjod4lg0gchCgp1bxhj6EA1cg/gwcXCVeIyQJrxxjDXsqeqFnC6ifYp2D\ncyZdPhQa31Pvj+tlAfw8/GmFZ70XoulUwi5Qj2rptB39mwxKWGQTIPzd+8jEIC+Z\nMy8xj70fLIGTpSKcZ/AF3jrAoQKBgQDQHeVRAD8JEAqYyzWbz25cSkwQnv9t2pHj\nuFr4Kyrd20rhei6Y8/eqQ354nXYc+HOBJ6ZpafjT9s5DDUK93MK4nEekShnYSzxc\nChuZ1g+9NJZjI+zMqNU08SNGVVrBjpVDlFUcfd9BE9d6RDlEwWLU3MbrvSe+K5Mv\nKVO/9NBX/wKBgBRDtTRR0z5aIRV6YxDXTrm2U8GcaLB5znEh8OmF/tA2rgy7V+tX\nqoK+OhP/0nVLW60H53bhK/nRAq1Nmrd8E8E1iqXiLENq2nOjVUvXLoiTeSUSi1kg\nG0gjzpyODUoO5oDYh0+6i77P8WZ19qdHSYsuGFMpWms3ZuVDdELJa9chAoGAbM+E\nqvIfAwUBFVwBvmIYyGYMGRCYaf5CEra70U74jaBvKS5xmITN85ZwVG23aHQ6J8fs\nSOcgMuqycvpG7++xW0ZSasJXeu/zMggS4D68YedRzanl0Cdhudlt4QMVfWeoAPpX\n+ZqSFHtkSMfMzXbyzmpUEsMGOXac8KaB5DYCjE8CgYATVtesBazJJXhCA+DnAbYS\naTnFRgES/FO1WLJ4xIzE+6zvIRwXREQM1ymw52yRBNp7O4PYxAviJBkaeyNNpEn0\n6ixfgYKGM0gNbE1+34ixZ172ergXj4ti4/KqROdHXmNrn0r8uLqilqE2dHh2LagH\nE3YRCDLH3H6kxv8PePmXGQ==\n-----END PRIVATE KEY-----\n"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-n4aon@ingrevia.iam.gserviceaccount.com"
  JWT_SECRET: "my-strong-random-secret-key"
  FIREBASE_BUCKET: "https://console.firebase.google.com/u/0/project/ingrevia/storage/ingrevia.firebasestorage.app/files"
  
handlers:
  - url: /static
    static_dir: static/
  
  - url: /.*
    script: auto
